'use client';

import { useState } from 'react';
import { colors, spacing, typography, borderRadius, shadows, transitions } from './styles';
import type { Idea, IdeaExperiment, IdeaSignal } from '@prisma/client';

type IdeaWithExperiments = Idea & {
  experiments: IdeaExperiment[];
};

interface IdeaCardProps {
  idea: IdeaWithExperiments;
  signalMap: Record<string, { source: string; content: string }>;
  onStateChange?: (ideaId: string, newState: string) => void;
}

export function IdeaCard({ idea, signalMap, onStateChange }: IdeaCardProps) {
  const [showDetails, setShowDetails] = useState(false);
  const [showSignals, setShowSignals] = useState(false);
  const [showExperiments, setShowExperiments] = useState(false);

  const filterStatuses = [
    { label: 'Market/ARPU', value: idea.passesMarket },
    { label: 'Regulation/Safety', value: idea.passesRegulation },
    { label: 'Agent Fit', value: idea.passesAgentFit },
    { label: 'Founder Fit', value: idea.passesFounderFit }
  ];

  const scores = [
    { label: 'Pain & Frequency', value: idea.painFrequencyScore },
    { label: 'Agent Leverage', value: idea.agentLeverageScore },
    { label: 'Data Surface', value: idea.dataSurfaceScore },
    { label: 'Repeatability', value: idea.repeatabilityScore },
    { label: 'Total', value: idea.totalScore }
  ];

  const getScoreColor = (score: number | null | undefined) => {
    if (!score) return colors.score.none;
    if (score >= 9) return colors.score.high;
    if (score >= 7) return colors.score.medium;
    return colors.score.low;
  };

  return (
    <div
      style={{
        border: `1px solid ${colors.ui.border}`,
        borderRadius: borderRadius.md,
        padding: spacing.md,
        backgroundColor: colors.ui.background,
        cursor: 'pointer',
        transition: `all ${transitions.normal}`,
        boxShadow: shadows.sm,
      }}
      onClick={() => setShowDetails(!showDetails)}
      onMouseEnter={(e) => {
        e.currentTarget.style.boxShadow = shadows.md;
        e.currentTarget.style.transform = 'translateY(-2px)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.boxShadow = shadows.sm;
        e.currentTarget.style.transform = 'translateY(0)';
      }}
    >
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'start',
          marginBottom: spacing.sm,
          gap: spacing.sm,
        }}
      >
        <h3
          style={{
            margin: 0,
            fontSize: typography.sizes.base,
            fontWeight: typography.weights.semibold,
            color: colors.ui.text.primary,
            flex: 1,
            lineHeight: 1.4,
          }}
        >
          {idea.title}
        </h3>
        {idea.totalScore !== null && (
          <span
            style={{
              backgroundColor: getScoreColor(idea.totalScore),
              color: 'white',
              borderRadius: borderRadius.full,
              padding: `${spacing.xs} ${spacing.sm}`,
              fontSize: typography.sizes.sm,
              fontWeight: typography.weights.bold,
              minWidth: '32px',
              textAlign: 'center',
              flexShrink: 0,
              boxShadow: shadows.sm,
            }}
          >
            {idea.totalScore}
          </span>
        )}
      </div>

      <p
        style={{
          margin: `${spacing.xs} 0`,
          fontSize: typography.sizes.sm,
          color: colors.ui.text.secondary,
          lineHeight: 1.5,
        }}
      >
        {idea.description}
      </p>

      {idea.autoGenerated && (
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: spacing.xs,
            color: colors.score.high,
            fontWeight: typography.weights.semibold,
            fontSize: typography.sizes.xs,
            margin: `${spacing.xs} 0`,
            padding: `${spacing.xs} ${spacing.sm}`,
            backgroundColor: `${colors.score.high}15`,
            borderRadius: borderRadius.sm,
          }}
        >
          ✨ Auto-generated from signals
        </div>
      )}

      {showDetails && (
        <div
          style={{
            marginTop: spacing.md,
            paddingTop: spacing.md,
            borderTop: `1px solid ${colors.ui.border}`,
          }}
        >
          {idea.transformation && (
            <div
              style={{
                marginBottom: spacing.md,
                padding: spacing.sm,
                backgroundColor: colors.ui.surface,
                borderRadius: borderRadius.sm,
              }}
            >
              <strong
                style={{
                  fontSize: typography.sizes.sm,
                  color: colors.ui.text.primary,
                  display: 'block',
                  marginBottom: spacing.xs,
                }}
              >
                Transformation:
              </strong>
              <p
                style={{
                  fontSize: typography.sizes.sm,
                  margin: 0,
                  color: colors.ui.text.secondary,
                  lineHeight: 1.5,
                }}
              >
                {idea.transformation}
              </p>
            </div>
          )}

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
              gap: spacing.md,
              marginBottom: spacing.md,
            }}
          >
            <div
              style={{
                padding: spacing.sm,
                backgroundColor: colors.ui.surface,
                borderRadius: borderRadius.sm,
              }}
            >
              <h4
                style={{
                  fontSize: typography.sizes.sm,
                  fontWeight: typography.weights.semibold,
                  margin: 0,
                  marginBottom: spacing.xs,
                  color: colors.ui.text.primary,
                }}
              >
                Hard Filters
              </h4>
              <ul
                style={{
                  fontSize: typography.sizes.xs,
                  margin: 0,
                  paddingLeft: spacing.md,
                  listStyle: 'none',
                }}
              >
                {filterStatuses.map((filter) => (
                  <li
                    key={filter.label}
                    style={{
                      marginBottom: spacing.xs,
                      display: 'flex',
                      alignItems: 'center',
                      gap: spacing.xs,
                    }}
                  >
                    <span style={{ fontSize: '1rem' }}>
                      {filter.value ? '✅' : '❌'}
                    </span>
                    <span
                      style={{
                        color: filter.value
                          ? colors.score.high
                          : colors.score.low,
                      }}
                    >
                      {filter.label}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
            <div
              style={{
                padding: spacing.sm,
                backgroundColor: colors.ui.surface,
                borderRadius: borderRadius.sm,
              }}
            >
              <h4
                style={{
                  fontSize: typography.sizes.sm,
                  fontWeight: typography.weights.semibold,
                  margin: 0,
                  marginBottom: spacing.xs,
                  color: colors.ui.text.primary,
                }}
              >
                Scores
              </h4>
              <ul
                style={{
                  fontSize: typography.sizes.xs,
                  margin: 0,
                  paddingLeft: spacing.md,
                  listStyle: 'none',
                }}
              >
                {scores.map((score) => (
                  <li
                    key={score.label}
                    style={{
                      marginBottom: spacing.xs,
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                    }}
                  >
                    <span style={{ color: colors.ui.text.secondary }}>
                      {score.label}:
                    </span>
                    <span
                      style={{
                        fontWeight: typography.weights.semibold,
                        color:
                          score.value !== null && score.value !== undefined
                            ? getScoreColor(score.value)
                            : colors.ui.text.tertiary,
                      }}
                    >
                      {score.value ?? '-'}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Signals Panel */}
          {(idea.sourceSignalIds ?? []).length > 0 && (
            <div style={{ marginTop: spacing.md }}>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setShowSignals(!showSignals);
                }}
                style={{
                  background: 'none',
                  border: 'none',
                  color: colors.ui.accent,
                  cursor: 'pointer',
                  fontSize: typography.sizes.sm,
                  fontWeight: typography.weights.semibold,
                  padding: 0,
                  marginBottom: spacing.xs,
                  display: 'flex',
                  alignItems: 'center',
                  gap: spacing.xs,
                  transition: `color ${transitions.fast}`,
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.color = colors.ui.accent;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.color = colors.ui.accent;
                }}
              >
                <span>{showSignals ? '▼' : '▶'}</span>
                <span>
                  Source Signals ({idea.sourceSignalIds.length})
                </span>
              </button>
              {showSignals && (
                <div
                  style={{
                    marginTop: spacing.sm,
                    padding: spacing.sm,
                    backgroundColor: colors.ui.surface,
                    borderRadius: borderRadius.sm,
                    border: `1px solid ${colors.ui.border}`,
                  }}
                >
                  <ul
                    style={{
                      fontSize: typography.sizes.xs,
                      margin: 0,
                      paddingLeft: spacing.md,
                      listStyle: 'none',
                    }}
                  >
                    {(idea.sourceSignalIds ?? []).map((signalId: string) => {
                      const signal = signalMap[signalId];
                      if (!signal) return null;
                      return (
                        <li
                          key={signalId}
                          style={{
                            marginBottom: spacing.sm,
                            paddingBottom: spacing.sm,
                            borderBottom: `1px solid ${colors.ui.border}`,
                          }}
                        >
                          <strong
                            style={{
                              color: colors.ui.text.primary,
                              display: 'block',
                              marginBottom: spacing.xs,
                            }}
                          >
                            {signal.source}:
                          </strong>
                          <span style={{ color: colors.ui.text.secondary }}>
                            {signal.content.slice(0, 120)}
                            {signal.content.length > 120 && '...'}
                          </span>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              )}
            </div>
          )}

          {/* Experiments Panel */}
          {idea.experiments.length > 0 && (
            <div style={{ marginTop: spacing.md }}>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setShowExperiments(!showExperiments);
                }}
                style={{
                  background: 'none',
                  border: 'none',
                  color: colors.ui.accent,
                  cursor: 'pointer',
                  fontSize: typography.sizes.sm,
                  fontWeight: typography.weights.semibold,
                  padding: 0,
                  marginBottom: spacing.xs,
                  display: 'flex',
                  alignItems: 'center',
                  gap: spacing.xs,
                }}
              >
                <span>{showExperiments ? '▼' : '▶'}</span>
                <span>Experiments ({idea.experiments.length})</span>
              </button>
              {showExperiments && (
                <div
                  style={{
                    marginTop: spacing.sm,
                    padding: spacing.sm,
                    backgroundColor: colors.ui.surface,
                    borderRadius: borderRadius.sm,
                    border: `1px solid ${colors.ui.border}`,
                  }}
                >
                  <ul
                    style={{
                      fontSize: typography.sizes.xs,
                      margin: 0,
                      paddingLeft: 0,
                      listStyle: 'none',
                    }}
                  >
                    {idea.experiments.map((experiment) => {
                      const resultColor =
                        experiment.result === 'PASSED'
                          ? colors.score.high
                          : experiment.result === 'FAILED'
                            ? colors.score.low
                            : colors.ui.text.tertiary;
                      return (
                        <li
                          key={experiment.id}
                          style={{
                            marginBottom: spacing.sm,
                            paddingBottom: spacing.sm,
                            borderBottom: `1px solid ${colors.ui.border}`,
                          }}
                        >
                          <div
                            style={{
                              display: 'flex',
                              justifyContent: 'space-between',
                              alignItems: 'start',
                              gap: spacing.xs,
                            }}
                          >
                            <div style={{ flex: 1 }}>
                              <span
                                style={{
                                  fontWeight: typography.weights.semibold,
                                  color: colors.ui.text.primary,
                                  fontSize: typography.sizes.xs,
                                }}
                              >
                                [{experiment.type}]
                              </span>{' '}
                              <span style={{ color: colors.ui.text.secondary }}>
                                {experiment.description.slice(0, 100)}
                                {experiment.description.length > 100 && '...'}
                              </span>
                            </div>
                            <span
                              style={{
                                color: resultColor,
                                fontWeight: typography.weights.bold,
                                fontSize: typography.sizes.xs,
                                flexShrink: 0,
                              }}
                            >
                              {experiment.result || 'PENDING'}
                            </span>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              )}
            </div>
          )}

          <div
            style={{
              display: 'flex',
              gap: spacing.sm,
              flexWrap: 'wrap',
              marginTop: spacing.md,
              paddingTop: spacing.md,
              borderTop: `1px solid ${colors.ui.border}`,
            }}
          >
            <form
              action="/founder/ideas"
              method="POST"
              onClick={(e) => e.stopPropagation()}
            >
              <input type="hidden" name="ideaId" value={idea.id} />
              <input type="hidden" name="action" value="evaluate" />
              <button
                type="submit"
                style={{
                  padding: `${spacing.xs} ${spacing.sm}`,
                  fontSize: typography.sizes.xs,
                  fontWeight: typography.weights.medium,
                  backgroundColor: colors.ui.accent,
                  color: 'white',
                  border: 'none',
                  borderRadius: borderRadius.sm,
                  cursor: 'pointer',
                  transition: `all ${transitions.fast}`,
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.opacity = '0.9';
                  e.currentTarget.style.transform = 'translateY(-1px)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.opacity = '1';
                  e.currentTarget.style.transform = 'translateY(0)';
                }}
              >
                Re-score
              </button>
            </form>

            <select
              defaultValue={idea.state}
              onChange={(e) => {
                if (onStateChange) {
                  onStateChange(idea.id, e.target.value);
                }
              }}
              onClick={(e) => e.stopPropagation()}
              style={{
                padding: `${spacing.xs} ${spacing.sm}`,
                fontSize: typography.sizes.xs,
                fontWeight: typography.weights.medium,
                border: `1px solid ${colors.ui.border}`,
                borderRadius: borderRadius.sm,
                backgroundColor: colors.ui.background,
                color: colors.ui.text.primary,
                cursor: 'pointer',
                transition: `all ${transitions.fast}`,
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = colors.ui.accent;
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = colors.ui.border;
              }}
            >
              <option value="PENDING_REVIEW">Pending Review</option>
              <option value="BACKLOG">Backlog</option>
              <option value="SCORING">Scoring</option>
              <option value="EXPERIMENTING">Experimenting</option>
              <option value="VALIDATED">Validated</option>
              <option value="KILLED">Killed</option>
            </select>
          </div>
        </div>
      )}
    </div>
  );
}

