'use client';

import { useState } from 'react';
import type { Idea, IdeaExperiment, IdeaSignal } from '@prisma/client';

type IdeaWithExperiments = Idea & {
  experiments: IdeaExperiment[];
};

interface IdeaCardProps {
  idea: IdeaWithExperiments;
  signalMap: Record<string, { source: string; content: string }>;
  onStateChange?: (ideaId: string, newState: string) => void;
}

export function IdeaCard({ idea, signalMap, onStateChange }: IdeaCardProps) {
  const [showDetails, setShowDetails] = useState(false);
  const [showSignals, setShowSignals] = useState(false);
  const [showExperiments, setShowExperiments] = useState(false);

  const filterStatuses = [
    { label: 'Market/ARPU', value: idea.passesMarket },
    { label: 'Regulation/Safety', value: idea.passesRegulation },
    { label: 'Agent Fit', value: idea.passesAgentFit },
    { label: 'Founder Fit', value: idea.passesFounderFit }
  ];

  const scores = [
    { label: 'Pain & Frequency', value: idea.painFrequencyScore },
    { label: 'Agent Leverage', value: idea.agentLeverageScore },
    { label: 'Data Surface', value: idea.dataSurfaceScore },
    { label: 'Repeatability', value: idea.repeatabilityScore },
    { label: 'Total', value: idea.totalScore }
  ];

  const getScoreColor = (score: number | null | undefined) => {
    if (!score) return '#9ca3af';
    if (score >= 9) return '#10b981'; // green
    if (score >= 7) return '#f59e0b'; // yellow
    return '#ef4444'; // red
  };

  return (
    <div
      style={{
        border: '1px solid #e5e7eb',
        borderRadius: '0.5rem',
        padding: '1rem',
        backgroundColor: 'white',
        cursor: 'pointer',
        transition: 'all 0.2s',
        boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)'
      }}
      onClick={() => setShowDetails(!showDetails)}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '0.5rem' }}>
        <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 600 }}>
          {idea.title}
        </h3>
        {idea.totalScore !== null && (
          <span
            style={{
              backgroundColor: getScoreColor(idea.totalScore),
              color: 'white',
              borderRadius: '9999px',
              padding: '0.125rem 0.5rem',
              fontSize: '0.75rem',
              fontWeight: 600,
              minWidth: '2rem',
              textAlign: 'center'
            }}
          >
            {idea.totalScore}
          </span>
        )}
      </div>

      <p style={{ margin: '0.5rem 0', fontSize: '0.875rem', color: '#6b7280' }}>
        {idea.description}
      </p>

      {idea.autoGenerated && (
        <p style={{ color: '#10b981', fontWeight: 600, fontSize: '0.75rem', margin: '0.5rem 0' }}>
          ✨ Auto-generated from signals
        </p>
      )}

      {showDetails && (
        <div style={{ marginTop: '1rem', paddingTop: '1rem', borderTop: '1px solid #e5e7eb' }}>
          {idea.transformation && (
            <div style={{ marginBottom: '1rem' }}>
              <strong style={{ fontSize: '0.875rem' }}>Transformation:</strong>
              <p style={{ fontSize: '0.875rem', margin: '0.25rem 0', color: '#4b5563' }}>
                {idea.transformation}
              </p>
            </div>
          )}

          <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', marginBottom: '1rem' }}>
            <div>
              <h4 style={{ fontSize: '0.875rem', marginBottom: '0.25rem' }}>Hard Filters</h4>
              <ul style={{ fontSize: '0.75rem', margin: 0, paddingLeft: '1.25rem' }}>
                {filterStatuses.map((filter) => (
                  <li key={filter.label}>
                    {filter.label}: {filter.value ? '✅' : '❌'}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 style={{ fontSize: '0.875rem', marginBottom: '0.25rem' }}>Scores</h4>
              <ul style={{ fontSize: '0.75rem', margin: 0, paddingLeft: '1.25rem' }}>
                {scores.map((score) => (
                  <li key={score.label}>
                    {score.label}: {score.value ?? '-'}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Signals Panel */}
          {(idea.sourceSignalIds ?? []).length > 0 && (
            <div style={{ marginTop: '1rem' }}>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setShowSignals(!showSignals);
                }}
                style={{
                  background: 'none',
                  border: 'none',
                  color: '#3b82f6',
                  cursor: 'pointer',
                  fontSize: '0.875rem',
                  fontWeight: 600,
                  padding: 0,
                  marginBottom: '0.5rem'
                }}
              >
                {showSignals ? '▼' : '▶'} Source Signals ({idea.sourceSignalIds.length})
              </button>
              {showSignals && (
                <ul style={{ fontSize: '0.75rem', margin: '0.5rem 0', paddingLeft: '1.25rem' }}>
                  {(idea.sourceSignalIds ?? []).map((signalId: string) => {
                    const signal = signalMap[signalId];
                    if (!signal) return null;
                    return (
                      <li key={signalId} style={{ marginBottom: '0.5rem' }}>
                        <strong>{signal.source}:</strong> {signal.content.slice(0, 100)}
                        {signal.content.length > 100 && '...'}
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>
          )}

          {/* Experiments Panel */}
          {idea.experiments.length > 0 && (
            <div style={{ marginTop: '1rem' }}>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setShowExperiments(!showExperiments);
                }}
                style={{
                  background: 'none',
                  border: 'none',
                  color: '#3b82f6',
                  cursor: 'pointer',
                  fontSize: '0.875rem',
                  fontWeight: 600,
                  padding: 0,
                  marginBottom: '0.5rem'
                }}
              >
                {showExperiments ? '▼' : '▶'} Experiments ({idea.experiments.length})
              </button>
              {showExperiments && (
                <ul style={{ fontSize: '0.75rem', margin: '0.5rem 0', paddingLeft: '1.25rem' }}>
                  {idea.experiments.map((experiment) => {
                    const resultColor =
                      experiment.result === 'PASSED'
                        ? '#10b981'
                        : experiment.result === 'FAILED'
                          ? '#ef4444'
                          : '#6b7280';
                    return (
                      <li key={experiment.id} style={{ marginBottom: '0.5rem' }}>
                        <span style={{ fontWeight: 600 }}>[{experiment.type}]</span>{' '}
                        {experiment.description.slice(0, 80)}
                        {experiment.description.length > 80 && '...'}
                        {' → '}
                        <span style={{ color: resultColor, fontWeight: 600 }}>
                          {experiment.result || 'PENDING'}
                        </span>
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>
          )}

          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginTop: '1rem' }}>
            <form
              action="/founder/ideas"
              method="POST"
              onClick={(e) => e.stopPropagation()}
            >
              <input type="hidden" name="ideaId" value={idea.id} />
              <input type="hidden" name="action" value="evaluate" />
              <button
                type="submit"
                style={{
                  padding: '0.25rem 0.5rem',
                  fontSize: '0.75rem',
                  backgroundColor: '#3b82f6',
                  color: 'white',
                  border: 'none',
                  borderRadius: '0.25rem',
                  cursor: 'pointer'
                }}
              >
                Re-score
              </button>
            </form>

            <select
              defaultValue={idea.state}
              onChange={(e) => {
                if (onStateChange) {
                  onStateChange(idea.id, e.target.value);
                }
              }}
              onClick={(e) => e.stopPropagation()}
              style={{
                padding: '0.25rem 0.5rem',
                fontSize: '0.75rem',
                border: '1px solid #d1d5db',
                borderRadius: '0.25rem',
                cursor: 'pointer'
              }}
            >
              <option value="PENDING_REVIEW">Pending Review</option>
              <option value="BACKLOG">Backlog</option>
              <option value="SCORING">Scoring</option>
              <option value="EXPERIMENTING">Experimenting</option>
              <option value="VALIDATED">Validated</option>
              <option value="KILLED">Killed</option>
            </select>
          </div>
        </div>
      )}
    </div>
  );
}

