import 'dotenv/config';
import { prisma } from '../src/l0/db.ts';

async function main() {
  const signals = await prisma.ideaSignal.findMany({
    orderBy: { createdAt: 'desc' },
    take: 10
  });

  const ideas = await prisma.idea.findMany({
    orderBy: { createdAt: 'desc' },
    take: 10
  });

  console.log('Latest idea signals:\n');
  for (const signal of signals) {
    console.log(
      `- ${signal.source} (${signal.createdAt.toISOString()}): ${signal.content.slice(0, 160)}`
    );
  }

  console.log('\nLatest ideas:\n');
  for (const idea of ideas) {
    console.log(
      `- ${idea.title} [${idea.state}] autoGenerated=${idea.autoGenerated} (signals: ${idea.sourceSignalIds.join(
        ', '
      )})`
    );
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });


